### ISSUE TITLE
Install errors with node v0.12

### ISSUE THREAD

**Issue by hertzg** [TritonDataCenter/node-statvfs#5]
Fails to build with node v0.12

```
$ npm install --save statvfs

> statvfs@2.1.0 install /home/hertz/projects/dango-device/node_modules/statvfs
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/hertz/projects/dango-device/node_modules/statvfs/build'
  CXX(target) Release/obj.target/statvfs/src/statvfs.o
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Local<v8::Object> build_stats_object(statvfs&)’:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/statvfs.cpp:90:14: error: within this context
  HandleScope scope;
              ^
../src/statvfs.cpp:92:36: error: no matching function for call to ‘v8::Object::New()’
  Local<Object> stats = Object::New();
                                    ^
../src/statvfs.cpp:92:36: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/statvfs.cpp:94:45: error: no matching function for call to ‘v8::Number::New(long unsigned int&)’
  stats->Set(bsize_sym, Number::New(s.f_bsize));
                                             ^
../src/statvfs.cpp:94:45: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:95:47: error: no matching function for call to ‘v8::Number::New(long unsigned int&)’
  stats->Set(frsize_sym, Number::New(s.f_frsize));
                                               ^
../src/statvfs.cpp:95:47: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:96:47: error: no matching function for call to ‘v8::Number::New(__fsblkcnt64_t&)’
  stats->Set(blocks_sym, Number::New(s.f_blocks));
                                               ^
../src/statvfs.cpp:96:47: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:97:45: error: no matching function for call to ‘v8::Number::New(__fsblkcnt64_t&)’
  stats->Set(bfree_sym, Number::New(s.f_bfree));
                                             ^
../src/statvfs.cpp:97:45: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:98:47: error: no matching function for call to ‘v8::Number::New(__fsblkcnt64_t&)’
  stats->Set(bavail_sym, Number::New(s.f_bavail));
                                               ^
../src/statvfs.cpp:98:47: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:99:45: error: no matching function for call to ‘v8::Number::New(__fsfilcnt64_t&)’
  stats->Set(files_sym, Number::New(s.f_files));
                                             ^
../src/statvfs.cpp:99:45: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:100:45: error: no matching function for call to ‘v8::Number::New(__fsfilcnt64_t&)’
  stats->Set(ffree_sym, Number::New(s.f_ffree));
                                             ^
../src/statvfs.cpp:100:45: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:101:47: error: no matching function for call to ‘v8::Number::New(__fsfilcnt64_t&)’
  stats->Set(favail_sym, Number::New(s.f_favail));
                                               ^
../src/statvfs.cpp:101:47: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:102:43: error: no matching function for call to ‘v8::Number::New(long unsigned int&)’
  stats->Set(fsid_sym, Number::New(s.f_fsid));
                                           ^
../src/statvfs.cpp:102:43: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:103:43: error: no matching function for call to ‘v8::Number::New(long unsigned int&)’
  stats->Set(flag_sym, Number::New(s.f_flag));
                                           ^
../src/statvfs.cpp:103:43: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:104:49: error: no matching function for call to ‘v8::Number::New(long unsigned int&)’
  stats->Set(namemax_sym, Number::New(s.f_namemax));
                                                 ^
../src/statvfs.cpp:104:49: note: candidate is:
In file included from /home/hertz/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/statvfs.cpp:10:
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/hertz/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/statvfs.cpp:106:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close(stats);
               ^
../src/statvfs.cpp: At global scope:
../src/statvfs.cpp:113:16: error: variable or field ‘_statvfs’ declared void
 void _statvfs (uv_work_t *req) {
                ^
../src/statvfs.cpp:113:16: error: ‘uv_work_t’ was not declared in this scope
../src/statvfs.cpp:113:27: error: ‘req’ was not declared in this scope
 void _statvfs (uv_work_t *req) {
                           ^
../src/statvfs.cpp:122:22: error: variable or field ‘_statvfs_after’ declared void
 void _statvfs_after (uv_work_t *req, int ignore_me_status_in_0_dot_10) {
                      ^
../src/statvfs.cpp:122:22: error: ‘uv_work_t’ was not declared in this scope
../src/statvfs.cpp:122:33: error: ‘req’ was not declared in this scope
 void _statvfs_after (uv_work_t *req, int ignore_me_status_in_0_dot_10) {
                                 ^
../src/statvfs.cpp:122:38: error: expected primary-expression before ‘int’
 void _statvfs_after (uv_work_t *req, int ignore_me_status_in_0_dot_10) {
                                      ^
../src/statvfs.cpp: In function ‘v8::Local<v8::Object> build_stats_object(statvfs&)’:
../src/statvfs.cpp:107:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
statvfs.target.mk:84: recipe for target 'Release/obj.target/statvfs/src/statvfs.o' failed
make: *** [Release/obj.target/statvfs/src/statvfs.o] Error 1
make: Leaving directory '/home/hertz/projects/dango-device/node_modules/statvfs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hertz/projects/dango-device/node_modules/statvfs
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "statvfs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! statvfs@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the statvfs@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the statvfs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls statvfs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hertz/projects/dango-device/npm-debug.log
```
